export const WISTIA_API_KEY = process.env.NEXT_PUBLIC_WISTIA_API_KEY;
export const SUPABASE_API_KEY = process.env.NEXT_PUBLIC_SUPABASE_API_KEY;
export const SUPABASE_PROJECT_URL = process.env.NEXT_PUBLIC_SUPABASE_PROJECT_URL;
